travis:
  secure:
    BINSTAR_TOKEN: xZ6ZDRQuBCqSi/Ex7ffLopX21a/+x9ReU8IYzX7kovIp1jncUZATfFAoQtPrty2Kq3p2I2YjXp9mgnLIRZzrzxSc41NnROFOi5kfbX4047/VEfYuUXjPq624PIO7DOYH2o/BD72N3/TD5SDsErM8Y1C9Q2Hfuuv5zS8GgG1yJRkv4lg13Upyk8vvjztWI2QOXOt09JX43sfHLEDmmtPS8JKsNqN6gFEyMZZ1XhSmXD/oeXSLCuZCzEYjKRkg7J/4uNHKXta2aVdFeAvvIQ/y4iG77Ssuyo78+dBHry3ODdPIjmMyu4XIwgnLzk5cg1UF/1Ww0B1sZH4oeON68CONfP8LsgoGoJ4Qk4Fy4DsMiP/2XZgbUK7+zZXhmmYEkF/q/wUz0FZRb9mqf5ATqyIlZW1IEnT6O9CZUJ7H+mXgy1fMLvH5BhXGWr8Hxkmw9P6qruqPjj9CB6KvdSKNZUoKpM0z9J47wV1qn/hsJQx2QTjwtxyUrJePsVMY8nYza/6B0Fkq3st+gAH1qwaAg32iymwBNy+w5EZNUbHGAUhuSxks89duinhuCCpZh5BdqfwzI94iXXvfutxylFkCHrogTGjLC5gpHn0yp5lpcmPRyroD7KyArk2aia6Gj+WrcloKbiMTCxPvmCCIts+yep21O6wkxrP6ij5qtphQNGIWGkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
